name: rightsstatements
url: //h2481931.stratoserver.net:4000
canonical_url: //rightsstatements.org
markdown: kramdown
kramdown:
  parse_block_html: true
highlighter: rouge
excerpt_separator: <!--more-->
exclude: [scripts]
defaults:
  -
    scope:
      path: "en"
    values:
      lang: "en"
      iso_name: "English"
  -
    scope:
      path: "de"
    values:
      lang: "de"
      iso_name: "Deutsch"
  -
    scope:
      path: "et"
    values:
      lang: "et"
      iso_name: "Eesti"
default_language: en
languages_enabled: yes
rights_app_server: //h2481931.stratoserver.net:9001
rights_data_version: 1.0
white_paper_tech_version: 180117requirements_for_the_technical_infrastructure_for_standardized_international_rights_statements_v1.2.1.pdf
white_paper_rs_version: 180531recommendations_for_standardized_international_rights_statements_v1.2.2.pdf
policy_editorial_version: 170612rs_editorial_policy.pdf
policy_translation_version: 170612rs_translation_policy.pdf
