# Site settings
email: your-email@domain.com
baseurl: ""
url: "http://literarymachine.github.io"
twitter_username: literarymachine
github_username:  literarymachine

# Build settings
markdown: kramdown

# Defaults for languages, no need specify them in the
# front-matter of every file.
defaults:
  -
    scope:
      path: en
    values:
      lang: en
  -
    scope:
      path: de
    values:
      lang: de

# Translations

t:
  en:
    title: Your English title
    description: >
      Write an awesome description for your new site here.
      You can use multiple lines.
  de:
    title: Dein deutscher Titel
    description: >
      Hier gehÃ¶rt eine Beschreibung fÃ¼r die neue Seite hin.
      Sie kann mehrere Zeilen umfassen.

enabled_languages:
  - en
  - de

default_language: en
